### ISSUE TITLE
ReferenceError Chart is not defined

### ISSUE THREAD

**Issue by real-yfprojects** [klausenbusk/flathub-stats#17] opened 2022-08-25 14:38 UTC
Just opened the website, layout unclean and entering an app in the text entry doesn't do anything.
The console reports the following errors in this order:
```
None of the “sha512” hashes in the integrity attribute match the content of the subresource. 3 [flathub-stats](https://klausenbusk.github.io/flathub-stats/)
```
```
Uncaught TypeError: t is undefined
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/chartjs-adapter-moment/1.0.0/chartjs-adapter-moment.min.js:7
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/chartjs-adapter-moment/1.0.0/chartjs-adapter-moment.min.js:7
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/chartjs-adapter-moment/1.0.0/chartjs-adapter-moment.min.js:7
[chartjs-adapter-moment.min.js:7:559](https://cdnjs.cloudflare.com/ajax/libs/chartjs-adapter-moment/1.0.0/chartjs-adapter-moment.min.js)
    <anonym> https://cdnjs.cloudflare.com/ajax/libs/chartjs-adapter-moment/1.0.0/chartjs-adapter-moment.min.js:7
    <anonym> https://cdnjs.cloudflare.com/ajax/libs/chartjs-adapter-moment/1.0.0/chartjs-adapter-moment.min.js:7
    <anonym> https://cdnjs.cloudflare.com/ajax/libs/chartjs-adapter-moment/1.0.0/chartjs-adapter-moment.min.js:7
```
```
Uncaught (in promise) ReferenceError: Chart is not defined
    initChart https://klausenbusk.github.io/flathub-stats/script.js:11
    init https://klausenbusk.github.io/flathub-stats/script.js:140
    EventListener.handleEvent* https://klausenbusk.github.io/flathub-stats/script.js:177
[script.js:11:2](https://klausenbusk.github.io/flathub-stats/script.js)
    init https://klausenbusk.github.io/flathub-stats/script.js:174
    (Async: EventListener.handleEvent)
    <anonym> https://klausenbusk.github.io/flathub-stats/script.js:177
```

**Comment by klausenbusk** [comment] 2022-08-26 18:57
I can't reproduce the issue in Firefox. What browser are you using? [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) isn't used, so I'm puzzled why you are getting that error.

**Comment by real-yfprojects** [comment] 2022-08-27 06:12
> I can't reproduce the issue in Firefox. What browser are you using?

Firefox

> [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) isn't used, so I'm puzzled why you are getting that error.

You are using it through the `integrity` attributes:
https://github.com/klausenbusk/flathub-stats/blob/817151076842dd3846ec3aa154bb92386b47c0fb/web/index.html#L6-L8
Based on you hint I also figured out the problem. I am using the [LocalCDN](https://codeberg.org/nobody/LocalCDN) browser plugin that replaces cdn resources by local copies that might differ from the web versions. This SRI prevents that.

**Comment by klausenbusk** [comment] 2022-08-27 15:05
> You are using it through the `integrity` attributes:
> https://github.com/klausenbusk/flathub-stats/blob/817151076842dd3846ec3aa154bb92386b47c0fb/web/index.html#L6-L8
> Based on you hint I also figured out the problem. I am using the [LocalCDN](https://codeberg.org/nobody/LocalCDN) browser plugin that replaces cdn resources by local copies that might differ from the web versions. This SRI prevents that. 

I'm using the same extension, which is why the `integrity` attributes was removed. I'm using the `Filter HTML source code` option, which removes the `integrity` attributes so LocalCDN can do its job.

Anyways, closing the issue as it is caused by a extension.

**Closed by klausenbusk** 2022-08-27 15:05 UTC
